# Generated by Django 3.1 on 2020-08-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eletro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=30)),
                ('capacidade', models.CharField(max_length=30)),
                ('onde_usamos', models.CharField(max_length=30)),
                ('preco', models.IntegerField()),
                ('ja_teve_conserto', models.BooleanField()),
            ],
        ),
    ]
